export type Language = 'en' | 'ta' | 'ml' | 'hi';

export const translations = {
  en: {
    // Onboarding
    appName: 'SmartPark',
    tagline: 'Parking Made Simple',
    getStarted: 'Get Started',
    findParking: 'Find Parking Instantly',
    findParkingDesc: 'Discover available parking spaces near you in real-time',
    aiPowered: 'AI-Powered Recommendations',
    aiPoweredDesc: 'Smart allocation based on distance, price, and popularity',
    secureBooking: 'Secure & Easy Booking',
    secureBookingDesc: 'Book and manage your parking with confidence',
    
    // Auth
    login: 'Login',
    signup: 'Sign Up',
    email: 'Email',
    password: 'Password',
    name: 'Name',
    selectRole: 'Select Role',
    driver: 'Driver',
    parkingOwner: 'Parking Owner',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    
    // Home - Driver
    explore: 'Explore',
    aiRecommendations: 'AI Recommendations',
    smartPick: 'Smart Pick',
    nearest: 'Nearest',
    cheapest: 'Cheapest',
    popular: 'Popular',
    noParkingAvailable: 'No parking spaces available',
    
    // Home - Owner
    dashboard: 'Dashboard',
    welcome: 'Welcome',
    totalSpaces: 'Total Spaces',
    available: 'Available',
    totalRevenue: 'Total Revenue',
    myParkingSpaces: 'My Parking Spaces',
    noParkingYet: 'No parking spaces yet',
    addFirstParking: 'Add your first parking space to start earning',
    addParking: 'Add Parking',
    
    // Bookings
    bookings: 'Bookings',
    myBookings: 'My Bookings',
    bookingRequests: 'Booking Requests',
    activeBookings: 'Active Bookings',
    pastBookings: 'Past Bookings',
    noBookingsYet: 'No bookings yet',
    bookParkingToSee: 'Book a parking space to see it here',
    bookingsWillAppear: 'Bookings will appear here when drivers book your spaces',
    cancelBooking: 'Cancel Booking',
    confirmCancel: 'Are you sure you want to cancel this booking?',
    
    // Profile
    profile: 'Profile',
    editProfile: 'Edit Profile',
    notifications: 'Notifications',
    paymentMethods: 'Payment Methods',
    helpSupport: 'Help & Support',
    privacyPolicy: 'Privacy Policy',
    language: 'Language',
    logout: 'Logout',
    confirmLogout: 'Are you sure you want to logout?',
    version: 'Version',
    
    // Parking Details
    parkingDetails: 'Parking Details',
    perHour: '/hour',
    location: 'Location',
    description: 'Description',
    features: 'Features',
    bookNow: 'Book Now',
    occupied: 'Occupied',
    
    // Booking Confirm
    confirmBooking: 'Confirm Booking',
    selectDateTime: 'Select Date & Time',
    startTime: 'Start Time',
    endTime: 'End Time',
    bookingSummary: 'Booking Summary',
    duration: 'Duration',
    rate: 'Rate',
    totalPrice: 'Total Price',
    hours: 'hours',
    confirming: 'Confirming...',
    
    // Add Parking
    addParkingSpace: 'Add Parking Space',
    parkingTitle: 'Parking Title',
    parkingType: 'Parking Type',
    carParking: 'Car Parking',
    bikeParking: 'Bike Parking',
    both: 'Both',
    spaceType: 'Space Type',
    house: 'House',
    apartment: 'Apartment',
    publicArea: 'Public Area',
    commercial: 'Commercial',
    address: 'Address',
    pricePerHour: 'Price per Hour',
    tapToSelectLocation: 'Tap to select location on map',
    selectOnMap: 'Select on Map',
    addFeatures: 'Add Features',
    covered: 'Covered',
    cctv: 'CCTV',
    security: '24/7 Security',
    evCharging: 'EV Charging',
    washroom: 'Washroom',
    create: 'Create',
    
    // AI Assistant
    aiAssistant: 'AI Assistant',
    askMeAnything: 'Ask me anything about parking...',
    howCanIHelp: 'How can I help you today?',
    send: 'Send',
    
    // Common
    cancel: 'Cancel',
    yes: 'Yes',
    no: 'No',
    ok: 'OK',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    success: 'Success',
    error: 'Error',
    loading: 'Loading...',
    comingSoon: 'Coming Soon',
    invalidTime: 'Invalid Time',
    endTimeAfterStart: 'End time must be after start time',
    bookingConfirmed: 'Booking confirmed successfully!',
    bookingCancelled: 'Booking cancelled successfully',
  },
  
  ta: {
    // Onboarding
    appName: 'ஸ்மார்ட்பார்க்',
    tagline: 'வாகன நிறுத்துதல் எளிதாக',
    getStarted: 'தொடங்குங்கள்',
    findParking: 'உடனடியாக பார்க்கிங் கண்டுபிடி',
    findParkingDesc: 'உங்களுக்கு அருகில் உள்ள வாகன நிறுத்துமிடங்களை நேரடியாக கண்டறியுங்கள்',
    aiPowered: 'AI-சக்தி பெற்ற பரிந்துரைகள்',
    aiPoweredDesc: 'தூரம், விலை மற்றும் புகழின் அடிப்படையில் புத்திசாலித்தனமான ஒதுக்கீடு',
    secureBooking: 'பாதுகாப்பான & எளிதான முன்பதிவு',
    secureBookingDesc: 'நம்பிக்கையுடன் உங்கள் பார்க்கிங்கை முன்பதிவு செய்து நிர்வகிக்கவும்',
    
    // Auth
    login: 'உள்நுழைய',
    signup: 'பதிவு செய்ய',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    name: 'பெயர்',
    selectRole: 'பங்கு தேர்ந்தெடுக்கவும்',
    driver: 'ஓட்டுநர்',
    parkingOwner: 'பார்க்கிங் உரிமையாளர்',
    alreadyHaveAccount: 'ஏற்கனவே கணக்கு உள்ளதா?',
    dontHaveAccount: 'கணக்கு இல்லையா?',
    
    // Home - Driver
    explore: 'ஆராயுங்கள்',
    aiRecommendations: 'AI பரிந்துரைகள்',
    smartPick: 'சிறந்த தேர்வு',
    nearest: 'அருகில்',
    cheapest: 'மலிவான',
    popular: 'பிரபலமான',
    noParkingAvailable: 'பார்க்கிங் இடங்கள் கிடைக்கவில்லை',
    
    // Home - Owner
    dashboard: 'டாஷ்போர்டு',
    welcome: 'வரவேற்கிறோம்',
    totalSpaces: 'மொத்த இடங்கள்',
    available: 'கிடைக்கும்',
    totalRevenue: 'மொத்த வருவாய்',
    myParkingSpaces: 'எனது பார்க்கிங் இடங்கள்',
    noParkingYet: 'இன்னும் பார்க்கிங் இடங்கள் இல்லை',
    addFirstParking: 'சம்பாதிக்க உங்கள் முதல் பார்க்கிங் இடத்தைச் சேர்க்கவும்',
    addParking: 'பார்க்கிங் சேர்',
    
    // Bookings
    bookings: 'முன்பதிவுகள்',
    myBookings: 'எனது முன்பதிவுகள்',
    bookingRequests: 'முன்பதிவு கோரிக்கைகள்',
    activeBookings: 'செயலில் உள்ள முன்பதிவுகள்',
    pastBookings: 'கடந்த முன்பதிவுகள்',
    noBookingsYet: 'இன்னும் முன்பதிவுகள் இல்லை',
    bookParkingToSee: 'பார்க்கிங் இடத்தை முன்பதிவு செய்து இங்கே காணவும்',
    bookingsWillAppear: 'ஓட்டுநர்கள் உங்கள் இடங்களை முன்பதிவு செய்யும் போது முன்பதிவுகள் தோன்றும்',
    cancelBooking: 'முன்பதிவை ரத்து செய்',
    confirmCancel: 'இந்த முன்பதிவை ரத்து செய்ய விரும்புகிறீர்களா?',
    
    // Profile
    profile: 'சுயவிவரம்',
    editProfile: 'சுயவிவரத்தைத் திருத்து',
    notifications: 'அறிவிப்புகள்',
    paymentMethods: 'கட்டண முறைகள்',
    helpSupport: 'உதவி & ஆதரவு',
    privacyPolicy: 'தனியுரிமை கொள்கை',
    language: 'மொழி',
    logout: 'வெளியேறு',
    confirmLogout: 'வெளியேற விரும்புகிறீர்களா?',
    version: 'பதிப்பு',
    
    // Parking Details
    parkingDetails: 'பார்க்கிங் விவரங்கள்',
    perHour: '/மணி',
    location: 'இடம்',
    description: 'விளக்கம்',
    features: 'அம்சங்கள்',
    bookNow: 'இப்போது முன்பதிவு செய்',
    occupied: 'ஆக்கிரமிக்கப்பட்டது',
    
    // Booking Confirm
    confirmBooking: 'முன்பதிவை உறுதிப்படுத்து',
    selectDateTime: 'தேதி & நேரத்தைத் தேர்ந்தெடுக்கவும்',
    startTime: 'தொடக்க நேரம்',
    endTime: 'முடிவு நேரம்',
    bookingSummary: 'முன்பதிவு சுருக்கம்',
    duration: 'கால அளவு',
    rate: 'விகிதம்',
    totalPrice: 'மொத்த விலை',
    hours: 'மணி',
    confirming: 'உறுதிப்படுத்துகிறது...',
    
    // Add Parking
    addParkingSpace: 'பார்க்கிங் இடம் சேர்',
    parkingTitle: 'பார்க்கிங் தலைப்பு',
    parkingType: 'பார்க்கிங் வகை',
    carParking: 'கார் பார்க்கிங்',
    bikeParking: 'பைக் பார்க்கிங்',
    both: 'இரண்டும்',
    spaceType: 'இட வகை',
    house: 'வீடு',
    apartment: 'அபார்ட்மெண்ட்',
    publicArea: 'பொது இடம்',
    commercial: 'வணிக',
    address: 'முகவரி',
    pricePerHour: 'ஒரு மணி நேர விலை',
    tapToSelectLocation: 'வரைபடத்தில் இடத்தைத் தேர்ந்தெடுக்க தட்டவும்',
    selectOnMap: 'வரைபடத்தில் தேர்ந்தெடு',
    addFeatures: 'அம்சங்கள் சேர்',
    covered: 'மூடப்பட்ட',
    cctv: 'CCTV',
    security: '24/7 பாதுகாப்பு',
    evCharging: 'EV சார்ஜிங்',
    washroom: 'கழிவறை',
    create: 'உருவாக்கு',
    
    // AI Assistant
    aiAssistant: 'AI உதவியாளர்',
    askMeAnything: 'பார்க்கிங் பற்றி எதையும் கேளுங்கள்...',
    howCanIHelp: 'இன்று நான் உங்களுக்கு எவ்வாறு உதவ முடியும்?',
    send: 'அனுப்பு',
    
    // Common
    cancel: 'ரத்து',
    yes: 'ஆம்',
    no: 'இல்லை',
    ok: 'சரி',
    save: 'சேமி',
    delete: 'நீக்கு',
    edit: 'திருத்து',
    success: 'வெற்றி',
    error: 'பிழை',
    loading: 'ஏற்றுகிறது...',
    comingSoon: 'விரைவில்',
    invalidTime: 'தவறான நேரம்',
    endTimeAfterStart: 'முடிவு நேரம் தொடக்க நேரத்திற்குப் பிறகு இருக்க வேண்டும்',
    bookingConfirmed: 'முன்பதிவு வெற்றிகரமாக உறுதிப்படுத்தப்பட்டது!',
    bookingCancelled: 'முன்பதிவு வெற்றிகரமாக ரத்து செய்யப்பட்டது',
  },
  
  ml: {
    // Onboarding
    appName: 'സ്മാർട്ട്പാർക്ക്',
    tagline: 'പാർക്കിംഗ് ലളിതമാക്കി',
    getStarted: 'ആരംഭിക്കുക',
    findParking: 'ഉടനടി പാർക്കിംഗ് കണ്ടെത്തുക',
    findParkingDesc: 'തത്സമയം നിങ്ങൾക്ക് സമീപമുള്ള പാർക്കിംഗ് സ്ഥലങ്ങൾ കണ്ടെത്തുക',
    aiPowered: 'AI-പവർഡ് ശുപാർശകൾ',
    aiPoweredDesc: 'ദൂരം, വില, ജനപ്രീതി എന്നിവയെ അടിസ്ഥാനമാക്കിയുള്ള സ്മാർട്ട് അലോക്കേഷൻ',
    secureBooking: 'സുരക്ഷിതവും എളുപ്പവുമായ ബുക്കിംഗ്',
    secureBookingDesc: 'ആത്മവിശ്വാസത്തോടെ നിങ്ങളുടെ പാർക്കിംഗ് ബുക്ക് ചെയ്യുകയും മാനേജ് ചെയ്യുകയും ചെയ്യുക',
    
    // Auth
    login: 'ലോഗിൻ',
    signup: 'സൈൻ അപ്പ്',
    email: 'ഇമെയിൽ',
    password: 'പാസ്‌വേഡ്',
    name: 'പേര്',
    selectRole: 'റോൾ തിരഞ്ഞെടുക്കുക',
    driver: 'ഡ്രൈവർ',
    parkingOwner: 'പാർക്കിംഗ് ഉടമ',
    alreadyHaveAccount: 'ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ?',
    dontHaveAccount: 'അക്കൗണ്ട് ഇല്ലേ?',
    
    // Home - Driver
    explore: 'പര്യവേക്ഷണം',
    aiRecommendations: 'AI ശുപാർശകൾ',
    smartPick: 'മികച്ച തിരഞ്ഞെടുപ്പ്',
    nearest: 'അടുത്തത്',
    cheapest: 'വിലകുറഞ്ഞത്',
    popular: 'ജനപ്രിയം',
    noParkingAvailable: 'പാർക്കിംഗ് സ്ഥലങ്ങൾ ലഭ്യമല്ല',
    
    // Home - Owner
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    welcome: 'സ്വാഗതം',
    totalSpaces: 'മൊത്തം സ്ഥലങ്ങൾ',
    available: 'ലഭ്യമാണ്',
    totalRevenue: 'മൊത്തം വരുമാനം',
    myParkingSpaces: 'എന്റെ പാർക്കിംഗ് സ്ഥലങ്ങൾ',
    noParkingYet: 'ഇതുവരെ പാർക്കിംഗ് സ്ഥലങ്ങളൊന്നുമില്ല',
    addFirstParking: 'സമ്പാദിക്കാൻ നിങ്ങളുടെ ആദ്യ പാർക്കിംഗ് സ്ഥലം ചേർക്കുക',
    addParking: 'പാർക്കിംഗ് ചേർക്കുക',
    
    // Bookings
    bookings: 'ബുക്കിംഗുകൾ',
    myBookings: 'എന്റെ ബുക്കിംഗുകൾ',
    bookingRequests: 'ബുക്കിംഗ് അഭ്യർത്ഥനകൾ',
    activeBookings: 'സജീവ ബുക്കിംഗുകൾ',
    pastBookings: 'മുൻകാല ബുക്കിംഗുകൾ',
    noBookingsYet: 'ഇതുവരെ ബുക്കിംഗുകളൊന്നുമില്ല',
    bookParkingToSee: 'ഇവിടെ കാണാൻ പാർക്കിംഗ് സ്ഥലം ബുക്ക് ചെയ്യുക',
    bookingsWillAppear: 'ഡ്രൈവർമാർ നിങ്ങളുടെ സ്ഥലങ്ങൾ ബുക്ക് ചെയ്യുമ്പോൾ ബുക്കിംഗുകൾ ഇവിടെ ദൃശ്യമാകും',
    cancelBooking: 'ബുക്കിംഗ് റദ്ദാക്കുക',
    confirmCancel: 'ഈ ബുക്കിംഗ് റദ്ദാക്കണമെന്ന് ഉറപ്പാണോ?',
    
    // Profile
    profile: 'പ്രൊഫൈൽ',
    editProfile: 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യുക',
    notifications: 'അറിയിപ്പുകൾ',
    paymentMethods: 'പേയ്‌മെന്റ് രീതികൾ',
    helpSupport: 'സഹായം & പിന്തുണ',
    privacyPolicy: 'സ്വകാര്യതാ നയം',
    language: 'ഭാഷ',
    logout: 'ലോഗൗട്ട്',
    confirmLogout: 'ലോഗൗട്ട് ചെയ്യണമെന്ന് ഉറപ്പാണോ?',
    version: 'പതിപ്പ്',
    
    // Parking Details
    parkingDetails: 'പാർക്കിംഗ് വിശദാംശങ്ങൾ',
    perHour: '/മണിക്കൂർ',
    location: 'സ്ഥലം',
    description: 'വിവരണം',
    features: 'സവിശേഷതകൾ',
    bookNow: 'ഇപ്പോൾ ബുക്ക് ചെയ്യുക',
    occupied: 'കൈവശപ്പെടുത്തി',
    
    // Booking Confirm
    confirmBooking: 'ബുക്കിംഗ് സ്ഥിരീകരിക്കുക',
    selectDateTime: 'തീയതിയും സമയവും തിരഞ്ഞെടുക്കുക',
    startTime: 'ആരംഭ സമയം',
    endTime: 'അവസാന സമയം',
    bookingSummary: 'ബുക്കിംഗ് സംഗ്രഹം',
    duration: 'കാലാവധി',
    rate: 'നിരക്ക്',
    totalPrice: 'മൊത്തം വില',
    hours: 'മണിക്കൂർ',
    confirming: 'സ്ഥിരീകരിക്കുന്നു...',
    
    // Add Parking
    addParkingSpace: 'പാർക്കിംഗ് സ്ഥലം ചേർക്കുക',
    parkingTitle: 'പാർക്കിംഗ് ശീർഷകം',
    parkingType: 'പാർക്കിംഗ് തരം',
    carParking: 'കാർ പാർക്കിംഗ്',
    bikeParking: 'ബൈക്ക് പാർക്കിംഗ്',
    both: 'രണ്ടും',
    spaceType: 'സ്പേസ് തരം',
    house: 'വീട്',
    apartment: 'അപ്പാർട്ട്മെന്റ്',
    publicArea: 'പൊതു പ്രദേശം',
    commercial: 'വാണിജ്യം',
    address: 'വിലാസം',
    pricePerHour: 'ഓരോ മണിക്കൂറിനും വില',
    tapToSelectLocation: 'മാപ്പിൽ സ്ഥലം തിരഞ്ഞെടുക്കാൻ ടാപ്പ് ചെയ്യുക',
    selectOnMap: 'മാപ്പിൽ തിരഞ്ഞെടുക്കുക',
    addFeatures: 'സവിശേഷതകൾ ചേർക്കുക',
    covered: 'മൂടിയ',
    cctv: 'CCTV',
    security: '24/7 സുരക്ഷ',
    evCharging: 'EV ചാർജിംഗ്',
    washroom: 'വാഷ്റൂം',
    create: 'സൃഷ്ടിക്കുക',
    
    // AI Assistant
    aiAssistant: 'AI അസിസ്റ്റന്റ്',
    askMeAnything: 'പാർക്കിംഗിനെക്കുറിച്ച് എന്തും ചോദിക്കൂ...',
    howCanIHelp: 'ഇന്ന് ഞാൻ നിങ്ങളെ എങ്ങനെ സഹായിക്കും?',
    send: 'അയയ്ക്കുക',
    
    // Common
    cancel: 'റദ്ദാക്കുക',
    yes: 'അതെ',
    no: 'ഇല്ല',
    ok: 'ശരി',
    save: 'സേവ് ചെയ്യുക',
    delete: 'ഇല്ലാതാക്കുക',
    edit: 'എഡിറ്റ് ചെയ്യുക',
    success: 'വിജയം',
    error: 'പിശക്',
    loading: 'ലോഡുചെയ്യുന്നു...',
    comingSoon: 'ഉടൻ വരുന്നു',
    invalidTime: 'അസാധുവായ സമയം',
    endTimeAfterStart: 'അവസാന സമയം ആരംഭ സമയത്തിന് ശേഷമായിരിക്കണം',
    bookingConfirmed: 'ബുക്കിംഗ് വിജയകരമായി സ്ഥിരീകരിച്ചു!',
    bookingCancelled: 'ബുക്കിംഗ് വിജയകരമായി റദ്ദാക്കി',
  },
  
  hi: {
    // Onboarding
    appName: 'स्मार्टपार्क',
    tagline: 'पार्किंग सरल बनी',
    getStarted: 'शुरू करें',
    findParking: 'तुरंत पार्किंग खोजें',
    findParkingDesc: 'अपने आस-पास उपलब्ध पार्किंग स्थानों को वास्तविक समय में खोजें',
    aiPowered: 'AI-संचालित सिफारिशें',
    aiPoweredDesc: 'दूरी, कीमत और लोकप्रियता के आधार पर स्मार्ट आवंटन',
    secureBooking: 'सुरक्षित और आसान बुकिंग',
    secureBookingDesc: 'विश्वास के साथ अपनी पार्किंग बुक करें और प्रबंधित करें',
    
    // Auth
    login: 'लॉगिन',
    signup: 'साइन अप',
    email: 'ईमेल',
    password: 'पासवर्ड',
    name: 'नाम',
    selectRole: 'भूमिका चुनें',
    driver: 'ड्राइवर',
    parkingOwner: 'पार्किंग मालिक',
    alreadyHaveAccount: 'पहले से खाता है?',
    dontHaveAccount: 'खाता नहीं है?',
    
    // Home - Driver
    explore: 'अन्वेषण करें',
    aiRecommendations: 'AI सिफारिशें',
    smartPick: 'स्मार्ट चयन',
    nearest: 'निकटतम',
    cheapest: 'सबसे सस्ता',
    popular: 'लोकप्रिय',
    noParkingAvailable: 'कोई पार्किंग स्थान उपलब्ध नहीं',
    
    // Home - Owner
    dashboard: 'डैशबोर्ड',
    welcome: 'स्वागत है',
    totalSpaces: 'कुल स्थान',
    available: 'उपलब्ध',
    totalRevenue: 'कुल राजस्व',
    myParkingSpaces: 'मेरे पार्किंग स्थान',
    noParkingYet: 'अभी तक कोई पार्किंग स्थान नहीं',
    addFirstParking: 'कमाई शुरू करने के लिए अपना पहला पार्किंग स्थान जोड़ें',
    addParking: 'पार्किंग जोड़ें',
    
    // Bookings
    bookings: 'बुकिंग',
    myBookings: 'मेरी बुकिंग',
    bookingRequests: 'बुकिंग अनुरोध',
    activeBookings: 'सक्रिय बुकिंग',
    pastBookings: 'पिछली बुकिंग',
    noBookingsYet: 'अभी तक कोई बुकिंग नहीं',
    bookParkingToSee: 'यहां देखने के लिए पार्किंग स्थान बुक करें',
    bookingsWillAppear: 'जब ड्राइवर आपके स्थान बुक करेंगे तो बुकिंग यहां दिखाई देगी',
    cancelBooking: 'बुकिंग रद्द करें',
    confirmCancel: 'क्या आप वाकई इस बुकिंग को रद्द करना चाहते हैं?',
    
    // Profile
    profile: 'प्रोफ़ाइल',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    notifications: 'सूचनाएं',
    paymentMethods: 'भुगतान के तरीके',
    helpSupport: 'सहायता और समर्थन',
    privacyPolicy: 'गोपनीयता नीति',
    language: 'भाषा',
    logout: 'लॉगआउट',
    confirmLogout: 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
    version: 'संस्करण',
    
    // Parking Details
    parkingDetails: 'पार्किंग विवरण',
    perHour: '/घंटा',
    location: 'स्थान',
    description: 'विवरण',
    features: 'सुविधाएं',
    bookNow: 'अभी बुक करें',
    occupied: 'कब्जा',
    
    // Booking Confirm
    confirmBooking: 'बुकिंग की पुष्टि करें',
    selectDateTime: 'तारीख और समय चुनें',
    startTime: 'प्रारंभ समय',
    endTime: 'समाप्ति समय',
    bookingSummary: 'बुकिंग सारांश',
    duration: 'अवधि',
    rate: 'दर',
    totalPrice: 'कुल कीमत',
    hours: 'घंटे',
    confirming: 'पुष्टि कर रहे हैं...',
    
    // Add Parking
    addParkingSpace: 'पार्किंग स्थान जोड़ें',
    parkingTitle: 'पार्किंग शीर्षक',
    parkingType: 'पार्किंग प्रकार',
    carParking: 'कार पार्किंग',
    bikeParking: 'बाइक पार्किंग',
    both: 'दोनों',
    spaceType: 'स्थान प्रकार',
    house: 'घर',
    apartment: 'अपार्टमेंट',
    publicArea: 'सार्वजनिक क्षेत्र',
    commercial: 'व्यावसायिक',
    address: 'पता',
    pricePerHour: 'प्रति घंटा कीमत',
    tapToSelectLocation: 'मानचित्र पर स्थान चुनने के लिए टैप करें',
    selectOnMap: 'मानचित्र पर चुनें',
    addFeatures: 'सुविधाएं जोड़ें',
    covered: 'कवर',
    cctv: 'CCTV',
    security: '24/7 सुरक्षा',
    evCharging: 'EV चार्जिंग',
    washroom: 'वॉशरूम',
    create: 'बनाएं',
    
    // AI Assistant
    aiAssistant: 'AI सहायक',
    askMeAnything: 'पार्किंग के बारे में कुछ भी पूछें...',
    howCanIHelp: 'आज मैं आपकी कैसे मदद कर सकता हूं?',
    send: 'भेजें',
    
    // Common
    cancel: 'रद्द करें',
    yes: 'हां',
    no: 'नहीं',
    ok: 'ठीक है',
    save: 'सहेजें',
    delete: 'हटाएं',
    edit: 'संपादित करें',
    success: 'सफलता',
    error: 'त्रुटि',
    loading: 'लोड हो रहा है...',
    comingSoon: 'जल्द आ रहा है',
    invalidTime: 'अमान्य समय',
    endTimeAfterStart: 'समाप्ति समय प्रारंभ समय के बाद होना चाहिए',
    bookingConfirmed: 'बुकिंग सफलतापूर्वक पुष्टि की गई!',
    bookingCancelled: 'बुकिंग सफलतापूर्वक रद्द की गई',
  },
};

export function getTranslation(lang: Language, key: keyof typeof translations.en): string {
  return translations[lang][key] || translations.en[key];
}
