import { ParkingSpace, Booking, User } from '@/types';

// Tamil Nadu cities with realistic coordinates
export const TAMIL_NADU_CITIES = [
  { name: 'Chennai', lat: 13.0827, lng: 80.2707 },
  { name: 'Coimbatore', lat: 11.0168, lng: 76.9558 },
  { name: 'Madurai', lat: 9.9252, lng: 78.1198 },
  { name: 'Tiruchirappalli', lat: 10.7905, lng: 78.7047 },
  { name: 'Salem', lat: 11.6643, lng: 78.1460 },
  { name: 'Tirunelveli', lat: 8.7139, lng: 77.7567 },
  { name: 'Tiruppur', lat: 11.1085, lng: 77.3411 },
  { name: 'Erode', lat: 11.3410, lng: 77.7172 },
  { name: 'Vellore', lat: 12.9165, lng: 79.1325 },
  { name: 'Thoothukudi', lat: 8.7642, lng: 78.1348 },
];

export const MOCK_PARKING_SPACES: ParkingSpace[] = [
  // Chennai
  {
    id: '1',
    ownerId: 'owner1',
    title: 'T Nagar Shopping Complex Parking',
    description: 'Covered parking near Pondy Bazaar shopping area',
    address: 'T Nagar, Chennai, Tamil Nadu',
    latitude: 13.0418,
    longitude: 80.2341,
    pricePerHour: 40,
    available: true,
    parkingType: 'both',
    spaceType: 'commercial',
    features: ['Covered', 'CCTV', '24/7 Security'],
    rating: 4.8,
    totalBookings: 156,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    ownerId: 'owner2',
    title: 'Anna Nagar Apartment Parking',
    description: 'Secure residential parking space available for rent',
    address: 'Anna Nagar West, Chennai, Tamil Nadu',
    latitude: 13.0878,
    longitude: 80.2085,
    pricePerHour: 25,
    available: true,
    parkingType: 'car',
    spaceType: 'apartment',
    features: ['Security Guard', 'Covered'],
    rating: 4.5,
    totalBookings: 89,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    ownerId: 'owner3',
    title: 'Velachery House Parking',
    description: 'Private house parking - Car and Bike available',
    address: 'Velachery, Chennai, Tamil Nadu',
    latitude: 12.9750,
    longitude: 80.2210,
    pricePerHour: 20,
    available: true,
    parkingType: 'both',
    spaceType: 'house',
    features: ['Private', 'Safe'],
    rating: 4.9,
    totalBookings: 45,
    createdAt: new Date().toISOString(),
  },
  
  // Coimbatore
  {
    id: '4',
    ownerId: 'owner1',
    title: 'RS Puram Market Parking',
    description: 'Central market area parking',
    address: 'RS Puram, Coimbatore, Tamil Nadu',
    latitude: 11.0063,
    longitude: 76.9615,
    pricePerHour: 30,
    available: true,
    parkingType: 'both',
    spaceType: 'commercial',
    features: ['Well-lit', 'CCTV'],
    rating: 4.6,
    totalBookings: 123,
    createdAt: new Date().toISOString(),
  },
  {
    id: '5',
    ownerId: 'owner2',
    title: 'Saibaba Colony Bike Parking',
    description: 'Two-wheeler parking near temple',
    address: 'Saibaba Colony, Coimbatore, Tamil Nadu',
    latitude: 11.0243,
    longitude: 76.9524,
    pricePerHour: 10,
    available: true,
    parkingType: 'bike',
    spaceType: 'public',
    features: ['Affordable', 'Safe'],
    rating: 4.4,
    totalBookings: 234,
    createdAt: new Date().toISOString(),
  },
  
  // Madurai
  {
    id: '6',
    ownerId: 'owner3',
    title: 'Meenakshi Temple Parking',
    description: 'Parking near famous Meenakshi Amman Temple',
    address: 'Near Meenakshi Temple, Madurai, Tamil Nadu',
    latitude: 9.9195,
    longitude: 78.1193,
    pricePerHour: 35,
    available: true,
    parkingType: 'both',
    spaceType: 'public',
    features: ['Large Space', '24/7', 'Security'],
    rating: 4.7,
    totalBookings: 312,
    createdAt: new Date().toISOString(),
  },
  {
    id: '7',
    ownerId: 'owner1',
    title: 'Anna Nagar Residential Parking',
    description: 'Quiet residential area parking',
    address: 'Anna Nagar, Madurai, Tamil Nadu',
    latitude: 9.9311,
    longitude: 78.1092,
    pricePerHour: 20,
    available: true,
    parkingType: 'car',
    spaceType: 'house',
    features: ['Residential', 'Peaceful'],
    rating: 4.5,
    totalBookings: 67,
    createdAt: new Date().toISOString(),
  },
  
  // Tiruchirappalli
  {
    id: '8',
    ownerId: 'owner2',
    title: 'Chathiram Bus Stand Parking',
    description: 'Convenient parking near bus stand',
    address: 'Chathiram Bus Stand, Trichy, Tamil Nadu',
    latitude: 10.8135,
    longitude: 78.6869,
    pricePerHour: 25,
    available: true,
    parkingType: 'both',
    spaceType: 'public',
    features: ['Central Location', 'Easy Access'],
    rating: 4.3,
    totalBookings: 189,
    createdAt: new Date().toISOString(),
  },
  
  // Salem
  {
    id: '9',
    ownerId: 'owner3',
    title: 'Junction Shopping Parking',
    description: 'Mall parking with covered space',
    address: 'Junction, Salem, Tamil Nadu',
    latitude: 11.6551,
    longitude: 78.1569,
    pricePerHour: 30,
    available: true,
    parkingType: 'car',
    spaceType: 'commercial',
    features: ['Covered', 'Shopping Area', 'CCTV'],
    rating: 4.6,
    totalBookings: 201,
    createdAt: new Date().toISOString(),
  },
  {
    id: '10',
    ownerId: 'owner1',
    title: 'Hasthampatti Apartment Parking',
    description: 'Gated community parking space',
    address: 'Hasthampatti, Salem, Tamil Nadu',
    latitude: 11.6372,
    longitude: 78.1574,
    pricePerHour: 15,
    available: true,
    parkingType: 'both',
    spaceType: 'apartment',
    features: ['Gated', 'Secure', 'Affordable'],
    rating: 4.8,
    totalBookings: 98,
    createdAt: new Date().toISOString(),
  },
];

export const generateMockBookings = (userId: string, isDriver: boolean): Booking[] => {
  const now = new Date();
  const bookings: Booking[] = [];

  if (isDriver) {
    bookings.push({
      id: 'b1',
      parkingSpaceId: '1',
      driverId: userId,
      startTime: new Date(now.getTime() + 2 * 60 * 60 * 1000).toISOString(),
      endTime: new Date(now.getTime() + 5 * 60 * 60 * 1000).toISOString(),
      totalPrice: 120,
      status: 'confirmed',
      createdAt: now.toISOString(),
      parkingSpace: MOCK_PARKING_SPACES[0],
    });
  }

  return bookings;
};
